import { IncrementDiscriptionParts } from '../models/increment-discription-parts';

const MATERIAL_SET: IncrementDiscriptionParts = {
  name: true,
  alertLimit: true,
  shortDiscription: true,
  slider: false,
  universityGenenrate: false,
  prodTable: true,
  madeByTable: false,
  experiment: false,
  hire: false,
  teamwork: false,
  twin: false,
};

const FUNGUS_SET: IncrementDiscriptionParts = {
  name: true,
  alertLimit: true,
  shortDiscription: true,
  slider: true,
  universityGenenrate: false,
  prodTable: true,
  madeByTable: true,
  experiment: true,
  hire: false,
  teamwork: false,
  twin: false,
};

const FULL_SET: IncrementDiscriptionParts = {
  name: true,
  alertLimit: false,
  shortDiscription: true,
  slider: true,
  universityGenenrate: false,
  prodTable: true,
  madeByTable: false,
  experiment: false,
  hire: true,
  teamwork: true,
  twin: true,
};

const FULL_PLUS_SET: IncrementDiscriptionParts = {
  name: true,
  alertLimit: false,
  shortDiscription: true,
  slider: true,
  universityGenenrate: false,
  prodTable: true,
  madeByTable: true,
  experiment: false,
  hire: true,
  teamwork: true,
  twin: true,
};

const UNIVERSITY_SET: IncrementDiscriptionParts = {
  name: true,
  alertLimit: false,
  shortDiscription: true,
  slider: true,
  universityGenenrate: true,
  prodTable: true,
  madeByTable: false,
  experiment: false,
  hire: true,
  teamwork: false,
  twin: false,
};

const MACHINERY_SET: IncrementDiscriptionParts = {
  name: true,
  alertLimit: false,
  shortDiscription: true,
  slider: true,
  universityGenenrate: false,
  prodTable: true,
  madeByTable: true,
  experiment: false,
  hire: true,
  teamwork: false,
  twin: false,
};

export const INCREMENT_DISCREPTION_LATOUT_CONFIG = {
  food: MATERIAL_SET,
  crystal: MATERIAL_SET,
  soil: MATERIAL_SET,
  science: MATERIAL_SET,
  fungus: FUNGUS_SET,
  wood: MATERIAL_SET,
  sand: MATERIAL_SET,
  geologist: FULL_SET,
  farmer: FULL_SET,
  carpenter: FULL_SET,
  lumberjack: FULL_SET,
  hunter: FULL_SET,
  advancedHunter: FULL_SET,
  composterAnt: FULL_SET,
  refineryAnt: FULL_SET,
  laserAnt: FULL_SET,
  hydroponicAnt: FULL_SET,
  planterAnt: FULL_SET,
  nest: FULL_SET,
  queen: FULL_PLUS_SET,
  ant: FULL_PLUS_SET,
  student: FULL_PLUS_SET,
  scientistAnt: FULL_PLUS_SET,
  university: UNIVERSITY_SET,
  composterStation: MACHINERY_SET,
  refineryStation: MACHINERY_SET,
  laserStation: MACHINERY_SET,
  hydroponicFarm: MACHINERY_SET,
  plantingMachine: MACHINERY_SET,
  composterE: FULL_SET,
  refineE: FULL_SET,
  laserE: FULL_SET,
  hydroE: FULL_SET,
  plantingE: FULL_SET,
};
